#!/usr/bin/env python3

import logging
#logging.basicConfig(filename='test.log', level=logging.DEBUG)
#logger = logging.getLogger("netmiko")

import click
import yaml
import nak

import warnings
warnings.simplefilter("ignore")

def_inv = 'hosts'

@click.command()
@click.option('-s', '--simulate', 's', help="simulate", is_flag=True)
@click.option('-v', '--verbose', 'v', help="verbose output", is_flag=True)
@click.option('-l', '--limit', 'lim', help="limit actions to hostnames or shorthostnames", multiple=True)
@click.option('-i', '--inventory', 'inv', help="ansible inventory file (default: %s)" % def_inv, type=click.Path(exists=True), default=def_inv)
@click.option('-p', '--vaultpasswd', 'vault_pass', help="ansible vault password", default=None)
def main(s, v, lim, inv, vault_pass):
  """
  Interact with the boxes defined in Ansible inventory. Download config or take YML file, translate
  it to box config and print or apply it to a box.
  """
  if v:
    logging.basicConfig(level=logging.DEBUG)

  b = nak.Batch(simulate=s, limit=lim, inventory=inv, vault_pass=vault_pass)
  b.runAllSerial()


if __name__ == '__main__':
  main()

