#!/usr/bin/env python3

#import warnings
#warnings.simplefilter("ignore")

import click
import nak

@click.command()
@click.option('-t', '--type', 't', help="ios|nxos|dellos10", required=True)
@click.option('-h', '--host', 'h', help="hostname or IP")
@click.option('-u', '--user', 'u', help="user")
@click.option('-p', '--passwd', 'p', help="password/secret")
@click.option('-e', '--enable', 'e', help="enable secret")
@click.option('-d', '--download', 'd', help="download config and print running config", is_flag=True)
@click.option('-c', '--configure', 'c', help="configure from file", type=click.File())
@click.option('-s', '--simulate', 's', help="simulate", is_flag=True)
def main(t, h, u, p, e, d, c, s):
  """
  Interact with the box. Download config or take YML file, translate it to <type> config
  and print or apply it to a box.
  """

  b = nak.Box(t)
  b.connect(h, u, p, e)

  if d:
      print(b.getRunning())
  elif c:
    config = "\n".join(c.readlines())
    res = b.configure(config, s)
    if s:
      print(str(res))
  else:
    print("No action (download|apply) specified.")

  b.close()


if __name__ == '__main__':
  main()

