#!/usr/bin/env python3
# coding: utf-8

"""
box2yaml

Copyright (C) 2020 Tomas Hlavacek (tmshlvck@gmail.com)

This module is a part of Network Automation Toolkit.

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.
This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with
this program. If not, see <http://www.gnu.org/licenses/>.
"""

import yaml
import click
import nak

@click.command()
@click.option('-t', '--type', 't', help="ios|nxos|procurve|dellos10|ironware", required=True)
@click.option('-d', '--debug', 'debugparam', is_flag=True)
@click.option('-c', '--cutvlans', 'cutvlans', is_flag=True)
@click.argument('files', nargs=-1, type=click.File('r'))
def main(t, debugparam, cutvlans, files):
  if debugparam:
    logging.basicConfig(level=logging.DEBUG)

  cpo = nak.get_parser_object(t)
  for f in files:
    o = cpo(f.readlines())
    if cutvlans:
      del(o.cfg['vlans'])
    print(o.genYAML())
 

if __name__ == '__main__':
  main()

