#!/usr/bin/env python3
# coding: utf-8

"""
inv2csv

Copyright (C) 2020 Tomas Hlavacek (tmshlvck@gmail.com)

This module is a part of Network Automation Toolkit.

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.
This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with
this program. If not, see <http://www.gnu.org/licenses/>.
"""

import click
import nak.inventory
import sys


def_inv = ['/etc/ansible/hosts',]

@click.command()
@click.option('-l', '--limit', 'lim', help="limit actions to hostnames or shorthostnames", multiple=True)
@click.option('-i', '--inventory', 'invs', help="ansible inventory files (default: %s)" % str(def_inv), type=click.Path(exists=True), default=def_inv, multiple=True)
@click.option('-p', '--vaultpasswd', 'vault_pass', help="ansible vault password", default=None)
@click.option('-d', '--delimiter', 'delim', help="CSV field delimiter (default ':')", default=':')
def main(lim, invs, vault_pass, delim):
  """
  Generate CSV source not only for Oxidized based on Ansible inventory.
  """
  i = nak.inventory.AnsibleInventory(invs, vault_pass)
  hosts = i.getHosts(lim)

  for h in hosts:
    l = [h['inventory_hostname'], h['boxtype']]
    if 'ansible_user' in h and h['ansible_user']:
      l.append(h['ansible_user'])
    else:
      l.append('')
    if 'ansible_password' in h and h['ansible_password']:
      l.append(h['ansible_password'])
    else:
      l.append('')
    print(delim.join(l))

  return 0

if __name__ == '__main__':
  main()

