#!/usr/bin/env python3

import click
import nak.inventory
import sys


def_inv = 'hosts'


@click.command()
@click.option('-l', '--limit', 'lim', help="limit actions to hostnames or shorthostnames", multiple=True)
@click.option('-i', '--inventory', 'inv', help="ansible inventory file (default: %s)" % def_inv, type=click.Path(exists=True), default=def_inv)
@click.option('-p', '--vaultpasswd', 'vault_pass', help="ansible vault password", default=None)
def main(lim, inv, vault_pass):
  """
  Generate CSV source fox Oxidized based on Ansible inventory.
  """
  i = nak.inventory.AnsibleInventory([inv,], vault_pass)
  if lim:
    limit = lim
  else:
    limit = None
  hosts = i.getHosts(limit)

  for h in hosts:
    print("%s:%s:%s:%s" % (h['inventory_hostname'], h['model'], h['ansible_user'], h['ansible_password']))

  return 0 
  
if __name__ == '__main__':
  main()

