#!/usr/bin/env python3

import click
import nak.inventory
import sys


def_inv = 'hosts'


@click.command()
@click.option('-l', '--limit', 'lim', help="limit actions to hostnames or shorthostnames", multiple=True)
@click.option('-i', '--inventory', 'inv', help="ansible inventory file (default: %s)" % def_inv, type=click.Path(exists=True), default=def_inv)
@click.option('-p', '--vaultpasswd', 'vault_pass', help="ansible vault password", default=None)
@click.option('-d', '--delimiter', 'delim', help="CSV field delimiter (default ':')", default=':')
def main(lim, inv, vault_pass):
  """
  Generate CSV source not only for Oxidized based on Ansible inventory.
  """
  i = nak.inventory.AnsibleInventory(invs, vault_pass, delim)
  hosts = i.getHosts(lim)

  for h in hosts:
    print(delim.join(h['inventory_hostname'], h['boxtype'], h['ansible_user'], h['ansible_password']))

  return 0

if __name__ == '__main__':
  main()

