#!/usr/bin/env python3
# coding: utf-8

"""
nak

Copyright (C) 2020 Tomas Hlavacek (tmshlvck@gmail.com)

This module is a part of Network Automation Toolkit.

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.
This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with
this program. If not, see <http://www.gnu.org/licenses/>.
"""

import logging
#logging.basicConfig(filename='test.log', level=logging.DEBUG)
#logger = logging.getLogger("netmiko")

import click
import yaml
import nak

import warnings
warnings.simplefilter("ignore")

def_inv = ['/etc/ansible/hosts',]

@click.command()
@click.option('-s', '--simulate', 's', help="simulate", is_flag=True)
@click.option('-v', '--verbose', 'v', help="verbose output", is_flag=True)
@click.option('-r', '--serial', 'r', help="do not run in parallel", is_flag=True)
@click.option('-l', '--limit', 'lim', help="limit actions to hostnames or shorthostnames", multiple=True)
@click.option('-i', '--inventory', 'invs', help="ansible inventory files (default: %s)" % str(def_inv), type=click.Path(exists=True), default=def_inv, multiple=True)
@click.option('-p', '--vaultpasswd', 'vault_pass', help="ansible vault password", default=None)
def main(s, v, r, lim, invs, vault_pass):
  """
  Interact with the boxes defined in Ansible inventory. Download config or take YML file, translate
  it to box config and print or apply it to a box.
  """
  if v:
    logging.basicConfig(level=logging.DEBUG)

  b = nak.Batch(simulate=s, limit=lim, invs=invs, vault_pass=vault_pass)

  if r:
    b.runAllSerial()
  else:
    b.runAllParallel()


if __name__ == '__main__':
  main()

