#!/usr/bin/env python3

import logging
#logging.basicConfig(filename='test.log', level=logging.DEBUG)
#logger = logging.getLogger("netmiko")

import click
import yaml
import nak

import warnings
warnings.simplefilter("ignore")

def_inv = ['/etc/ansible/hosts',]

@click.command()
@click.option('-s', '--simulate', 's', help="simulate", is_flag=True)
@click.option('-v', '--verbose', 'v', help="verbose output", is_flag=True)
@click.option('-r', '--serial', 'r', help="do not run in parallel", is_flag=True)
@click.option('-l', '--limit', 'lim', help="limit actions to hostnames or shorthostnames", multiple=True)
@click.option('-i', '--inventory', 'invs', help="ansible inventory files (default: %s)" % str(def_inv), type=click.Path(exists=True), default=def_inv, multiple=True)
@click.option('-p', '--vaultpasswd', 'vault_pass', help="ansible vault password", default=None)
def main(s, v, r, lim, invs, vault_pass):
  """
  Interact with the boxes defined in Ansible inventory. Download config or take YML file, translate
  it to box config and print or apply it to a box.
  """
  if v:
    logging.basicConfig(level=logging.DEBUG)

  b = nak.Batch(simulate=s, limit=lim, invs=invs, vault_pass=vault_pass)

  if r:
    b.runAllSerial()
  else:
    b.runAllParallel()


if __name__ == '__main__':
  main()

