#!/usr/bin/env python3

import click
import yaml
import nak


@click.command()
@click.option('-t', '--type', 't', help="ios|nxos|dellos10", required=True)
@click.argument('yamlfiles', nargs=-1, type=click.File('r'))
def main(t, yamlfiles):
  """
  Generate a config for a box.
  """

  conf = nak.AnsibleInventoryPlayer.mergeConfigs(conf, [yaml.load(f, Loader=yaml.Loader) for f in yamlfiles])

  go = nak.get_gen_object(t)
  g = go(conf)
  print(g.genText())
  
if __name__ == '__main__':
  main()

